# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers

    working_directory: ~/testWorld

    steps:
      - checkout
     
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      #  && npm install chimp && chimp -v

      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: npm test
          command: npm test

      - run:
          name: test chimp
          command: chimp -v


